### ISSUE TITLE
Success method fails if the httpBody doesn't match the example in the specification

### ISSUE THREAD

**Issue by fabdrol** [mikermcneil/machinepack-mandrill#9]
The `success` method fails because the result from Mandrill doesn't match the example in the specification object. Is there any way to remove the validation on the success method? This behaviour is not useful when working with (unpredictable) web APIs. 

See also: https://github.com/node-machine/machinepack/issues/5

**Comment by sgress454** [comment]
See https://github.com/node-machine/machinepack/issues/5#issuecomment-169423107.

For future reference, this is referring to the `list-templates` machine specifically.

The issue is that the example is invalid.  Will fix and push up new version.  Thanks for the heads-up!
